
apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-app
  template:
    metadata:
      labels:
        app: churn-app
    spec:
      containers:
      - name: churn-container
        image: your-dockerhub-user/churn-app:latest
        ports:
        - containerPort: 8501
